services:
  - type: static_site
    name: MYCV
    repo: https://github.com/ons-taha/MYCV.git
    branch: main
    buildCommand: npm ci && npm run build
    publishPath: dist/freelance-cv
    nodeVersion: 20.x
